Repository ucsb-cs156-f23/proj-courses-f23-7pm-1, pull requests merged in 2023-11, with the labels that each got.

#17 Added course status to Course Search Results
  frontend/src/fixtures/sectionFixtures.js
  frontend/src/fixtures/sectionOverTimeFixtures.js
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/tests/components/Sections/SectionsOverTimeTable.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 10, Merge Candidate

#19 Refactoring Code
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeInstructorController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeInstructorControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsControllerTests.java
Labels: 5, Merge Candidate

#32 Frontend placeholder for Course Details page #13
  frontend/src/App.js
  frontend/src/main/pages/CourseDetails/CourseDetailsPage.js
  frontend/src/stories/pages/HomePage/CourseDetails/CourseDetailsIndexPage.stories.js
  frontend/src/tests/pages/CourseDetails/CourseDetailsPage.test.js
Labels: 10

#26 Add Course Details button to course search results
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/Sections/SectionsOverTimeTable.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 10

#27 Added Backend Endpoint to Retrieve Final Exam Information
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBFinalExamController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBFinalExamControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: 10, Merge Candidate

#29 GitHub Info Backend
  pom.xml
  src/main/java/edu/ucsb/cs156/courses/CoursesApplication.java
  src/main/java/edu/ucsb/cs156/courses/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/courses/services/SystemInfoServiceImpl.java
  src/test/java/edu/ucsb/cs156/courses/controllers/SystemInfoControllerTests.java
Labels: 10

#30 Add Developer Frontend Page
  frontend/src/App.js
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Developer/DeveloperTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/DeveloperPage.js
  frontend/src/stories/components/Developer/DeveloperTable.stories.js
  frontend/src/tests/components/Developer/DeveloperTable.test.js
  frontend/src/tests/pages/DeveloperPage.test.js
Labels: 10

#31 Implemented Admin Job to Update Final Exam Info
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/tests/pages/AdminJobsPage.test.js
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/courses/documents/ConvertedSection.java
  src/main/java/edu/ucsb/cs156/courses/documents/FinalExam.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateFinalsDataJob.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateFinalsDataJobFactory.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/documents/ConvertedSectionTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateFinalsDataJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateFinalsDataJobTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: 10, Merge Candidate

#39 Added Update Finals job form
  frontend/src/main/components/Jobs/UpdateFinalsJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/stories/components/Jobs/UpdateFinalsJobForm.stories.js
  frontend/src/tests/components/Jobs/UpdateFinalsJobForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10
